resources:
- name: repo
  type: git
  source:
    uri: https://github.com/matthiasbalke/infiniboard.git
    branch: concourse

- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:matthiasbalke/concourse_test.git
    branch: version
    file: version
    private_key: {{infiniboard-private-key}}
    initial_version: 1.0.0

- name: release-candidates
  type: s3
  source:
    bucket: infiniboard-rc
    regexp: infiniboard-(.*).jar
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    region_name: eu-central-1

- name: releases
  type: s3
  source:
    bucket: infiniboard-releases
    regexp: infiniboard-(.*).jar
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    region_name: eu-central-1

jobs:

- name: build-rc
  serial_groups: [version]
  plan:
  - get: repo
    trigger: true

  - get: version
    params: {bump: minor}

  - put: version
    params: {file: version/number}

  - task: build
    file: repo/ci/tasks/build.yml

  - put: release-candidates
    params:
      file: artifacts/infiniboard-*.jar
